spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

radion:
  security:
    encryption-key: ${ENCRYPTION_KEY}
  ai:
    provider: gemini # or openai
    system-instruction-path: "classpath:ai/system_instruction.md"
    command-schema-path: "classpath:ai/business_command_schema.json"
    gemini:
      api-key: ${GEMINI_API_KEY}
      model: ${GEMINI_MODEL:gemini-flash-latest}

    openai:

      api-key: ${OPENAI_API_KEY:}

logging:
  level:
    org.springframework.transaction: WARN
    org.springframework.orm.jpa: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI}